framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware:
                    allow_no_handlers: true

when@test:
    framework:
        messenger:
            buses:
                command.bus: ~
                query.bus: ~
                event.bus:
                    default_middleware:
                        allow_no_handlers: true
